=== Dakod/dnf_web_simulator/public/Resource/equipment.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.w3school.com.cn"
           xmlns="http://www.w3school.com.cn" elementFormDefault="qualified">

    <xs:simpleType name="grade_name">
        <xs:restriction base="xs:string">
            <xs:enumeration value="normal"/>
            <xs:enumeration value="senior"/>
            <xs:enumeration value="rare"/>
            <xs:enumeration value="artifact"/>
            <xs:enumeration value="legend"/>
            <xs:enumeration value="epic"/>
            <xs:enumeration value="myth"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="equipmentType_name">
        <xs:restriction base="xs:string">
            <xs:enumeration value="太刀"/>
            <xs:enumeration value="短剑"/>
            <xs:enumeration value="布甲"/>
            <xs:enumeration value="皮甲"/>
            <xs:enumeration value="轻甲"/>
            <xs:enumeration value="重甲"/>
            <xs:enumeration value="板甲"/>
            <xs:enumeration value="手镯"/>
            <xs:enumeration value="项链"/>
            <xs:enumeration value="耳环"/>
            <xs:enumeration value="戒指"/>
            <xs:enumeration value="辅助装备"/>
            <xs:enumeration value="耳环"/>
            <xs:enumeration value="魔法石"/>
            <xs:enumeration value="称号"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="equipment_level">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="100"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="skill_choose_type"> <!--选取某些技能的属性-->
        <xs:simpleContent>
            <xs:extension base="xs:integer">
                <xs:attribute name="type">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="range"/>
                            <xs:enumeration value="single"/>
                            <xs:enumeration value="talisman1"/>
                            <xs:enumeration value="talisman2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="start" type="xs:positiveInteger"/>
                <xs:attribute name="end" type="xs:positiveInteger"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="skill_choose_type_edit"> <!--选取某些技能的属性-->
        <xs:simpleContent>
            <xs:extension base="xs:integer">
                <xs:attribute name="min" type="xs:positiveInteger"/>
                <xs:attribute name="max" type="xs:positiveInteger"/>
                <xs:attribute name="step" type="xs:positiveInteger"/>
                <xs:attribute name="type">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="range"/>
                            <xs:enumeration value="single"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="start" type="xs:positiveInteger"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:attributeGroup name="min_max_step">
        <xs:attribute name="min" type="xs:positiveInteger"/>
        <xs:attribute name="max" type="xs:positiveInteger"/>
        <xs:attribute name="step" type="xs:positiveInteger"/>
    </xs:attributeGroup>

    <xs:complexType name="custom_positiveInteger">
        <xs:simpleContent>
            <xs:extension base="xs:positiveInteger">
                <xs:attribute name="isOutEffective"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="custom_decimal">
        <xs:simpleContent>
            <xs:extension base="xs:decimal">
                <xs:attribute name="isOutEffective"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="positiveInteger_min_max_step">
        <xs:simpleContent>
            <xs:extension base="xs:positiveInteger">
                <xs:attributeGroup ref="min_max_step"/>
                <xs:attribute name="isOutEffective"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="decimal_min_max_step">
        <xs:simpleContent>
            <xs:extension base="xs:decimal">
                <xs:attributeGroup ref="min_max_step"/>
                <xs:attribute name="isOutEffective"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>


    <xs:group name="common_property_group">
        <xs:choice>
            <xs:element name="PhyAtta" type="custom_positiveInteger"/>
            <xs:element name="MagAtta" type="custom_positiveInteger"/>
            <xs:element name="IndAtta" type="custom_positiveInteger"/>
            <xs:element name="Strength" type="custom_positiveInteger"/>
            <xs:element name="Intelligence" type="custom_positiveInteger"/>
            <xs:element name="StrengthIntelligence" type="custom_positiveInteger"/>
            <xs:element name="FourDimension" type="custom_positiveInteger"/>
            <xs:element name="PhyCrit" type="custom_decimal"/>
            <xs:element name="MagCrit" type="custom_decimal"/>
            <xs:element name="AllDamage" type="xs:positiveInteger"/>
            <xs:element name="AllAtta" type="custom_positiveInteger"/>
            <xs:element name="PropertyAtta">
                <xs:simpleType>
                    <xs:restriction base="xs:nonNegativeInteger">
                        <xs:minInclusive value="0"/>
                        <xs:maxInclusive value="5"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="SkillAtta" type="xs:positiveInteger"/>
            <xs:element name="TriAttaPercent" type="xs:integer"/>
            <xs:element name="StrengthPercent" type="xs:positiveInteger"/>
            <xs:element name="IntelligencePercent" type="xs:positiveInteger"/>
            <xs:element name="StrengthIntelligencePercent" type="xs:positiveInteger" minOccurs="0"
                        maxOccurs="unbounded"/>
            <xs:element name="ExtraYellow" type="xs:positiveInteger"/>
            <xs:element name="CritDamage" type="xs:positiveInteger"/>
            <xs:element name="ExtraCrit" type="xs:positiveInteger"/>
            <xs:element name="White" type="xs:positiveInteger"/>
            <xs:element name="AllStrengthen" type="custom_positiveInteger"/>
            <xs:element name="LightStrengthen" type="custom_positiveInteger"/>
            <xs:element name="DarkStrengthen" type="custom_positiveInteger"/>
            <xs:element name="IceStrengthen" type="custom_positiveInteger"/>
            <xs:element name="FireStrengthen" type="custom_positiveInteger"/>
            <xs:element name="Dot" type="xs:positiveInteger"/>
            <xs:element name="PropertyWhite" type="xs:positiveInteger"/>
            <xs:element name="SkillUp" type="skill_choose_type"/>
            <xs:element name="SkillLevel">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="skill_choose_type">
                            <xs:attribute name="condition">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="全部"/>
                                        <xs:enumeration value="主动"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:attribute>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="Cd" type="skill_choose_type"/>
        </xs:choice>
    </xs:group>

    <xs:group name="edit_property_group">
        <xs:choice>
            <xs:element name="PhyAtta" type="positiveInteger_min_max_step"/>
            <xs:element name="MagAtta" type="positiveInteger_min_max_step"/>
            <xs:element name="IndAtta" type="positiveInteger_min_max_step"/>
            <xs:element name="Strength" type="positiveInteger_min_max_step"/>
            <xs:element name="Intelligence" type="positiveInteger_min_max_step"/>
            <xs:element name="StrengthIntelligence" type="positiveInteger_min_max_step"/>
            <xs:element name="FourDimension" type="positiveInteger_min_max_step"/>
            <xs:element name="PhyCrit" type="xs:decimal"/>
            <xs:element name="MagCrit" type="xs:decimal"/>
            <xs:element name="AllDamage" type="positiveInteger_min_max_step"/>
            <xs:element name="AllAtta" type="positiveInteger_min_max_step"/>
            <xs:element name="SkillAtta" type="positiveInteger_min_max_step"/>
            <xs:element name="TriAttaPercent" type="positiveInteger_min_max_step"/>
            <xs:element name="StrengthPercent" type="positiveInteger_min_max_step"/>
            <xs:element name="IntelligencePercent" type="positiveInteger_min_max_step"/>
            <xs:element name="StrengthIntelligencePercent" type="positiveInteger_min_max_step"/>
            <xs:element name="ExtraYellow" type="positiveInteger_min_max_step"/>
            <xs:element name="CritDamage" type="positiveInteger_min_max_step"/>
            <xs:element name="ExtraCrit" type="positiveInteger_min_max_step"/>
            <xs:element name="White" type="positiveInteger_min_max_step"/>
            <xs:element name="AllStrengthen" type="positiveInteger_min_max_step"/>
            <xs:element name="LightStrengthen" type="positiveInteger_min_max_step"/>
            <xs:element name="DarkStrengthen" type="positiveInteger_min_max_step"/>
            <xs:element name="IceStrengthen" type="positiveInteger_min_max_step"/>
            <xs:element name="FireStrengthen" type="positiveInteger_min_max_step"/>
            <xs:element name="Dot" type="positiveInteger_min_max_step"/>

            <!--            <xs:element name="SkillUp" type="skill_choose_type_edit"/>-->
            <xs:element name="SkillLevel">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="skill_choose_type_edit">
                            <xs:attribute name="condition" use="required">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="全部"/>
                                        <xs:enumeration value="主动"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:attribute>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <!--            <xs:element name="Cd" type="skill_choose_type_edit"/>-->
        </xs:choice>
    </xs:group>

    <xs:complexType name="edit">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="Input">
                <xs:complexType>
                    <xs:group ref="edit_property_group"/>
                    <xs:attribute name="index" type="xs:nonNegativeInteger"/>
                    <xs:attribute name="title" type="xs:string"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="Selection">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Option" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:choice minOccurs="0" maxOccurs="unbounded">
                                    <xs:group ref="common_property_group"/>
                                    <xs:element name="Condition">
                                        <xs:complexType>
                                            <xs:group ref="common_property_group" maxOccurs="unbounded"/>
                                            <xs:attribute name="first" type="xs:string"/>
                                            <xs:attribute name="mid" type="xs:string"/>
                                            <xs:attribute name="last" type="xs:string"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:choice>
                                <xs:attribute name="value" type="xs:nonNegativeInteger"/>
                                <xs:attribute name="title" type="xs:string"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="index" type="xs:nonNegativeInteger"/>
                    <xs:attribute name="default" type="xs:nonNegativeInteger"/>
                    <xs:attribute name="title" type="xs:string"/>
                </xs:complexType>
            </xs:element>

        </xs:choice>
    </xs:complexType>

    <xs:complexType name="equipment_property">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:group ref="common_property_group"/>
                <xs:element name="StrengthNumUp">
                    <xs:complexType>
                        <xs:group ref="common_property_group"/>
                        <xs:attribute name="max" type="xs:positiveInteger"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Condition">
                    <xs:complexType>
                        <xs:group ref="common_property_group" maxOccurs="unbounded"/>
                        <xs:attribute name="first" type="xs:string"/>
                        <xs:attribute name="mid" type="xs:string"/>
                        <xs:attribute name="last" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
            <xs:element name="Edit" type="edit" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="equipment">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Grade" type="grade_name"/>
            <xs:element name="Type" type="equipmentType_name"/>
            <xs:element name="Level" type="equipment_level"/>
            <xs:element name="Property" type="equipment_property"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="suit" type="xs:integer"/>
        <xs:attribute name="editable" type="xs:boolean"/>
        <xs:attribute name="mythOf" type="xs:string"/>
    </xs:complexType>


    <xs:complexType name="equipment_list">
        <xs:sequence>
            <xs:element name="equipment" type="equipment" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="suit">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="ShortName" type="xs:string" minOccurs="0"/>
            <xs:element name="Property" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:complexContent>
                        <xs:extension base="equipment_property">
                            <xs:attribute name="num" type="xs:nonNegativeInteger"/>
                        </xs:extension>
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="type" type="xs:string"/>
        <xs:attribute name="higher" type="xs:string"/>
        <xs:attribute name="bind" type="xs:string"/>
        <xs:attribute name="link" type="xs:string"/>
        <xs:attribute name="editable" type="xs:boolean"/>
        <xs:attribute name="inCollection" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="suit_list">
        <xs:sequence>
            <xs:element name="suit" type="suit" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>


    <xs:element name="equipments">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="weapon">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="swordman" type="equipment_list"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="armor">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="shoulder" type="equipment_list"/>
                            <xs:element name="coat" type="equipment_list"/>
                            <xs:element name="pants" type="equipment_list"/>
                            <xs:element name="belt" type="equipment_list"/>
                            <xs:element name="shoes" type="equipment_list"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="jewelry">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="bracelet" type="equipment_list"/>
                            <xs:element name="necklace" type="equipment_list"/>
                            <xs:element name="ring" type="equipment_list"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="special">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="assistant" type="equipment_list"/>
                            <xs:element name="earrings" type="equipment_list"/>
                            <xs:element name="magicstone" type="equipment_list"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="titles">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="equipment_list"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="suits" type="suit_list"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Dakod/dnf_web_simulator/public/Resource/equipment.xml
<?xml version="1.0" encoding="UTF-8" ?><!--
装备编码规则
前两位代表装备类型 05 武器 01上衣 ...
第三位代表类型  050 太刀 010布甲上衣
之后三位表示装备等级
最后两位表示顺序号
例如: 05009000 圣耀救赎太刀
-->
<equipments xmlns="http://www.w3school.com.cn"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.w3school.com.cn equipment.xsd">
    <weapon>
        <swordman>
            <equipment id='0002178'>
                <Name>苍穹落幕太刀</Name>
                <Grade>epic</Grade>
                <Type>太刀</Type>
                <Level>95</Level>
                <Property>
                    <PhyAtta>1112</PhyAtta>
                    <MagAtta>1230</MagAtta>
                    <IndAtta>723</IndAtta>
                    <Strength>78</Strength>
                    <Intelligence>117</Intelligence>
                    <PhyCrit>2</PhyCrit>
                    <SkillAtta>45</SkillAtta>
                    <AllDamage>30</AllDamage>
                    <PropertyAtta>5</PropertyAtta>
                </Property>
            </equipment>
            <equipment id='0002191'>
                <Name>黑暗之主太刀</Name>
                <Grade>epic</Grade>
                <Type>太刀</Type>
                <Level>95</Level>
                <Property>
                    <PhyAtta>1112</PhyAtta>
                    <MagAtta>1230</MagAtta>
                    <IndAtta>723</IndAtta>
                    <Strength>78</Strength>
                    <Intelligence>117</Intelligence>
                    <PhyCrit>2</PhyCrit>
                    <SkillAtta>55</SkillAtta>
                    <AllDamage>32</AllDamage>
                    <PropertyAtta>5</PropertyAtta>
                </Property>
            </equipment>
            <equipment id='0002199' editable="true">
                <Name>太极天帝剑</Name>
                <Grade>epic</Grade>
                <Type>太刀</Type>
                <Level>100</Level>
                <Property>
                    <PhyAtta>1167</PhyAtta>
                    <MagAtta>1290</MagAtta>
                    <IndAtta>770</IndAtta>
                    <Strength>81</Strength>
                    <Intelligence>122</Intelligence>
                    <PhyCrit>2</PhyCrit>
                    <SkillAtta>30</SkillAtta>
                    <TriAttaPercent>40</TriAttaPercent>
                    <StrengthIntelligencePercent>10</StrengthIntelligencePercent>
                    <Edit>
                        <Selection index="0" default="0" title="阴气/阳气:">
                            <Option value="0" title="阴气:">
                                <AllDamage>21</AllDamage>
                            </Option>
                            <Option value="1" title="阳气:">
                                <SkillAtta>23</SkillAtta>
                            </Option>
                        </Selection>
                    </Edit>
                </Property>
            </equipment>
            <equipment id='0002181'>
                <Name>前瞻守卫者</Name>
                <Grade>epic</Grade>
                <Type>太刀</Type>
                <Level>100</Level>
                <Property>
                    <PhyAtta>1167</PhyAtta>
                    <MagAtta>1290</MagAtta>
                    <IndAtta>770</IndAtta>
                    <Strength>81</Strength>
                    <Intelligence>122</Intelligence>
                    <PhyCrit>2</PhyCrit>
                    <SkillAtta>35</SkillAtta>
                    <StrengthIntelligencePercent>25</StrengthIntelligencePercent>
                    <ExtraYellow>14</ExtraYellow>
                    <ExtraCrit>26</ExtraCrit>
                </Property>
            </equipment>
            <equipment id='0004166'>
                <Name>苍穹落幕短剑</Name>
                <Grade>epic</Grade>
                <Type>短剑</Type>
                <Level>95</Level>
                <Property>
                    <PhyAtta>1112</PhyAtta>
                    <MagAtta>1346</MagAtta>
                    <IndAtta>723</IndAtta>
                    <Intelligence>78</Intelligence>
                    <MagCrit>2</MagCrit>
                    <SkillAtta>45</SkillAtta>
                    <AllDamage>30</AllDamage>
                    <PropertyAtta>5</PropertyAtta>
                </Property>
            </equipment>
            <equipment id='0004174'>
                <Name>黑暗之主短剑</Name>
                <Grade>epic</Grade>
                <Type>短剑</Type>
                <Level>95</Level>
                <Property>
                    <PhyAtta>1112</PhyAtta>
                    <MagAtta>1346</MagAtta>
                    <IndAtta>723</IndAtta>
                    <Intelligence>78</Intelligence>
                    <MagCrit>2</MagCrit>
                    <SkillAtta>55</SkillAtta>
                    <AllDamage>32</AllDamage>
                    <PropertyAtta>5</PropertyAtta>
                </Property>
            </equipment>
            <equipment id='0004182'>
                <Name>信念徽章:自由</Name>
                <Grade>epic</Grade>
                <Type>短剑</Type>
                <Level>100</Level>
                <Property>
                    <PhyAtta>1167</PhyAtta>
                    <MagAtta>1414</MagAtta>
                    <IndAtta>770</IndAtta>
                    <Strength>81</Strength>
                    <MagCrit>2</MagCrit>
                    <SkillAtta>30</SkillAtta>
                    <StrengthIntelligencePercent>26</StrengthIntelligencePercent>
                    <TriAttaPercent>22</TriAttaPercent>
                    <ExtraYellow>22</ExtraYellow>
                </Property>
            </equipment>
            <equipment id='0004169'>
                <Name>战场的热血:安格巴迪</Name>
                <Grade>epic</Grade>
                <Type>短剑</Type>
                <Level>100</Level>
                <Property>
                    <PhyAtta>1167</PhyAtta>
                    <MagAtta>1414</MagAtta>
                    <IndAtta>770</IndAtta>
                    <Strength>81</Strength>
                    <PropertyAtta>0</PropertyAtta>
                    <MagCrit>2</MagCrit>
                    <SkillAtta>40</SkillAtta>
                    <ExtraCrit>30</ExtraCrit>
                    <ExtraYellow>34</ExtraYellow>
                </Property>
            </equipment>
        </swordman>
    </weapon>
    <armor>
        <shoulder>
            <!--95级-->
            <equipment id='0100071' suit="0001">
                <Name>超界·苍天之碧:卷云</Name>
                <Grade>epic</Grade>
                <Type>布甲</Type>
                <Level>95</Level>
                <Property>
                    <AllDamage>5</AllDamage>
                    <SkillAtta>20</SkillAtta>
                </Property>
            </equipment>
            <equipment id='0101068' suit="0003">
                <Name>超界·雨水:长青的群山</Name>
                <Grade>epic</Grade>
                <Type>皮甲</Type>
                <Level>95</Level>
                <Property>
                    <SkillLevel type="range" start="1" end="45" condition="全部">1</SkillLevel>
                    <White>20</White>
                </Property>
            </equipment>
            <equipment id='0102071' suit="0005">
                <Name>超界·北极星的魅力</Name>
                <Grade>epic</Grade>
                <Type>轻甲</Type>
                <Level>95</Level>
                <Property>
                    <PhyCrit>12</PhyCrit>
                    <MagCrit>12</MagCrit>
                    <SkillAtta>18</SkillAtta>
                </Property>
            </equipment>
            <equipment id='0103071' suit="0007">
                <Name>超界·梵雅的绝世容颜</Name>
                <Grade>epic</Grade>
                <Type>重甲</Type>
                <Level>95</Level>
                <Property>
                    <SkillAtta>23</SkillAtta>
                </Property>
            </equipment>
            <equipment id='0104069' suit="0009">
                <Name>超界·君清石的思念</Name>
                <Grade>epic</Grade>
                <Type>板甲</Type>
                <Level>95</Level>
                <Property>
                    <FireStrengthen>20</FireStrengthen>
                    <SkillAtta>17</SkillAtta>
                </Property>
            </equipment>
            <!--100级-->
            <!--布甲-->
            <equipment id='0100080' suit="0016">
                <Name>大祭司的星祈披肩</Name>
                <Grade>epic</Grade>
                <Type>布甲</Type>
                <Level>100</Level>
                <Property>
                    <StrengthIntelligencePercent>10</StrengthIntelligencePercent>
                    <TriAttaPercent>10</TriAttaPercent>
                    <SkillAtta>12</SkillAtta>
                </Property>
            </equipment>
            <equipment id='0100081' suit="0017">
                <Name>魔法师[???]的披风</Name>
                <Grade>epic</Grade>
                <Type>布甲</Type>
                <Level>100</Level>
                <Property>
                    <SkillAtta>13</SkillAtta>
                    <TriAttaPercent>10</TriAttaPercent>
                    <StrengthIntelligencePercent>5</StrengthIntelligencePercent>
                    <PhyCrit>5</PhyCrit>
                    <MagCrit>5</MagCrit>
                </Property>
            </equipment>
            <equipment id='0100082' suit="0018">
                <Name>性感洒脱探戈</Name>
                <Grade>epic</Grade>
                <Type>布甲</Type>
                <Level>100</Level>
                <Property>
                    <White>17</White>
                    <SkillAtta>14</SkillAtta>
                    <Cd type="range" start="75" end="80">-15</Cd>
                </Property>
            </equipment>
            <!--皮甲-->
            <equipment id='0101076' suit="0019">
                <Name>死亡阴影护肩</Name>
                <Grade>epic</Grade>
                <Type>皮甲</Type>
                <Level>100</Level>
                <Property>
                    <ExtraCrit>18</ExtraCrit>
                    <SkillAtta>10</SkillAtta>
